---
version: 2
jobs:
  build:
    docker:
      - image: library/docker:17
    working_directory: /tmp/build
    environment:
      DOCKER_USERNAME: travisciresin
      DOCKER_EMAIL: accounts+travisci+docker@resin.io
      DOCKER_IMAGE: resin/resin-base
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
          reusable: true
          exclusive: false
      - run: |
          docker info
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run:
          name: Build
          command: |
            set -x
            docker pull ${DOCKER_IMAGE}:${CIRCLE_BRANCH} || \
              docker pull ${DOCKER_IMAGE}:master || true
            docker build --rm=false --pull --tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} .
      - deploy:
          name: Push
          command: |
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            set -x
            docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:latest
            docker push ${DOCKER_IMAGE}:${CIRCLE_SHA1}
            docker push ${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            docker push ${DOCKER_IMAGE}:latest

            apk add --no-cache git
            tag=$(git describe --tags) || true
            if [ "${tag}" != "" ]; then
              docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:${tag}
              docker push ${DOCKER_IMAGE}:${tag}
            fi

